import {
  LATO_REGULAR,
  MERRIWEATHER_BOLD,
  MERRIWEATHER_LIGHT,
  MERRIWEATHER_REGULAR,
  MONTSERRAT_BOLD,
  MONTSERRAT_REGULAR,
  SACRAMENTO_REGULAR,
  SF_PRO_DISPLAY_MEDIUM,
  WALT_DISNEY,
} from '../constants';

export const Fonts = {
  LATO_REGULAR,
  MERRIWEATHER_LIGHT,
  MERRIWEATHER_BOLD,
  MERRIWEATHER_REGULAR,
  MONTSERRAT_BOLD,
  MONTSERRAT_REGULAR,
  SF_PRO_DISPLAY_MEDIUM,
  SACRAMENTO_REGULAR,
  WALT_DISNEY,
};
